//! Signed pod firmware with staged rollout.
//!
//! The property signs each image with its own ECDSA P-256 key
//! (`firmware keygen`); pods carry the public key and refuse any image whose
//! signature does not verify. A release is offered to `rollout_percent` of
//! the fleet, chosen by a stable hash of device id and version, so a canary
//! group updates first and the rest follow when the percentage is raised.

use std::path::{Path, PathBuf};

use ring::rand::SystemRandom;
use ring::signature::{
    EcdsaKeyPair, KeyPair, UnparsedPublicKey, ECDSA_P256_SHA256_ASN1,
    ECDSA_P256_SHA256_ASN1_SIGNING,
};
use rusqlite::{params, OptionalExtension};
use serde::Serialize;
use sha2::{Digest, Sha256};

use crate::store::TicketStore;
use crate::FacilitatorError;

#[derive(Clone, Debug, Serialize)]
pub struct FirmwareRelease {
    pub version: String,
    pub size: u64,
    pub sha256_hex: String,
    pub signature_hex: String,
    pub rollout_percent: u8,
    pub created_millis: i64,
}

/// Create a signing key (PKCS#8, owner-only) and return the public key as hex
/// (uncompressed SEC1 point) for the firmware build.
pub fn firmware_keygen(key_path: &Path) -> Result<String, FacilitatorError> {
    let rng = SystemRandom::new();
    let pkcs8 = EcdsaKeyPair::generate_pkcs8(&ECDSA_P256_SHA256_ASN1_SIGNING, &rng)
        .map_err(|_| FacilitatorError::Firmware("key generation failed".to_string()))?;
    let pair = load_pair(pkcs8.as_ref())?;
    crate::write_secret_file(key_path, &hex::encode(pkcs8.as_ref()))?;
    Ok(hex::encode(pair.public_key().as_ref()))
}

/// Public key for an existing signing key.
pub fn firmware_public_key(key_path: &Path) -> Result<String, FacilitatorError> {
    let pair = load_pair(&read_key(key_path)?)?;
    Ok(hex::encode(pair.public_key().as_ref()))
}

/// True when `signature_hex` is a valid signature of `image` by `public_key_hex`.
pub fn verify_firmware_signature(public_key_hex: &str, image: &[u8], signature_hex: &str) -> bool {
    match (hex::decode(public_key_hex), hex::decode(signature_hex)) {
        (Ok(public_key), Ok(signature)) => {
            UnparsedPublicKey::new(&ECDSA_P256_SHA256_ASN1, public_key)
                .verify(image, &signature)
                .is_ok()
        }
        _ => false,
    }
}

/// Sign `image`, copy it next to the property database, and record the release.
pub fn publish_firmware(
    database_path: &Path,
    key_path: &Path,
    image: &Path,
    version: &str,
    rollout_percent: u8,
) -> Result<FirmwareRelease, FacilitatorError> {
    let version = version.trim();
    if version.is_empty()
        || version.len() > 32
        || !version
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_'))
    {
        return Err(FacilitatorError::Firmware(
            "version must be 1-32 of letters, digits, '.', '-', '_'".to_string(),
        ));
    }
    let bytes = std::fs::read(image)?;
    let pair = load_pair(&read_key(key_path)?)?;
    let signature = pair
        .sign(&SystemRandom::new(), &bytes)
        .map_err(|_| FacilitatorError::Firmware("signing failed".to_string()))?;
    let target = image_path(database_path, version);
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&target, &bytes)?;
    let release = FirmwareRelease {
        version: version.to_string(),
        size: u64::try_from(bytes.len()).unwrap_or(u64::MAX),
        sha256_hex: hex::encode(Sha256::digest(&bytes)),
        signature_hex: hex::encode(signature.as_ref()),
        rollout_percent: rollout_percent.min(100),
        created_millis: crate::store::unix_millis(),
    };
    TicketStore::open(database_path)?.insert_firmware(&release)?;
    Ok(release)
}

/// Offer `version` to `percent` of the fleet.
pub fn set_firmware_rollout(
    database_path: &Path,
    version: &str,
    percent: u8,
) -> Result<(), FacilitatorError> {
    TicketStore::open(database_path)?.set_firmware_rollout(version.trim(), percent.min(100))
}

/// C header for a property's pod build: the CA pods trust, the key firmware
/// images must be signed with, and where the facilitator is.
pub fn pod_trust_header(ca_pem: &str, public_key_hex: &str, facilitator_url: &str) -> String {
    let ca = ca_pem.trim().replace(")PEM\"", "");
    let url = facilitator_url
        .trim()
        .trim_end_matches('/')
        .replace('"', "");
    let key = public_key_hex
        .chars()
        .filter(char::is_ascii_hexdigit)
        .collect::<String>();
    format!(
        "// Generated by `aice-<pack> property.json firmware pod-header`. Do not commit.\n\
        #pragma once\n\n\
        // Property CA: pods only talk to servers whose certificate it signed.\n\
        static const char PROPERTY_CA_PEM[] = R\"PEM({ca}\n)PEM\";\n\n\
        // ECDSA P-256 public key (uncompressed SEC1, hex) that signs firmware images.\n\
        static const char PROPERTY_FIRMWARE_PUBKEY_HEX[] = \"{key}\";\n\n\
        // Facilitator base URL for enrolment and updates.\n\
        static const char FACILITATOR_URL[] = \"{url}\";\n"
    )
}

/// Where a release's image is kept.
pub(crate) fn image_path(database_path: &Path, version: &str) -> PathBuf {
    database_path
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_default()
        .join("firmware")
        .join(format!("{version}.bin"))
}

/// Stable 0-99 bucket for a device and release.
pub(crate) fn cohort(device_id: &str, version: &str) -> u8 {
    let digest = Sha256::digest(format!("{device_id}/{version}").as_bytes());
    u8::try_from(u16::from_be_bytes([digest[0], digest[1]]) % 100).unwrap_or(99)
}

fn read_key(key_path: &Path) -> Result<Vec<u8>, FacilitatorError> {
    let text = std::fs::read_to_string(key_path)?;
    hex::decode(text.trim())
        .map_err(|error| FacilitatorError::Firmware(format!("{}: {error}", key_path.display())))
}

fn load_pair(pkcs8: &[u8]) -> Result<EcdsaKeyPair, FacilitatorError> {
    EcdsaKeyPair::from_pkcs8(&ECDSA_P256_SHA256_ASN1_SIGNING, pkcs8, &SystemRandom::new())
        .map_err(|error| FacilitatorError::Firmware(format!("signing key: {error}")))
}

impl TicketStore {
    pub(crate) fn insert_firmware(
        &self,
        release: &FirmwareRelease,
    ) -> Result<(), FacilitatorError> {
        self.with_connection(|connection| {
            connection.execute(
                "INSERT INTO firmware_releases (version, size, sha256_hex, signature_hex, rollout_percent, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6)
                 ON CONFLICT(version) DO UPDATE SET size = ?2, sha256_hex = ?3, signature_hex = ?4,
                    rollout_percent = ?5, created_at = ?6",
                params![
                    release.version,
                    i64::try_from(release.size).unwrap_or(i64::MAX),
                    release.sha256_hex,
                    release.signature_hex,
                    release.rollout_percent,
                    release.created_millis
                ],
            )?;
            crate::store::append_audit(
                connection,
                "admin",
                "firmware_published",
                None,
                None,
                None,
                &format!("{} at {}%", release.version, release.rollout_percent),
            )
        })
    }

    pub(crate) fn set_firmware_rollout(
        &self,
        version: &str,
        percent: u8,
    ) -> Result<(), FacilitatorError> {
        self.with_connection(|connection| {
            let changed = connection.execute(
                "UPDATE firmware_releases SET rollout_percent = ?1 WHERE version = ?2",
                params![percent, version],
            )?;
            if changed == 0 {
                return Err(FacilitatorError::Firmware(format!("no release {version}")));
            }
            crate::store::append_audit(
                connection,
                "admin",
                "firmware_rollout",
                None,
                None,
                None,
                &format!("{version} at {percent}%"),
            )
        })
    }

    /// The newest release.
    pub(crate) fn latest_firmware(&self) -> Result<Option<FirmwareRelease>, FacilitatorError> {
        self.with_connection(|connection| {
            connection
                .query_row(
                    "SELECT version, size, sha256_hex, signature_hex, rollout_percent, created_at
                     FROM firmware_releases ORDER BY created_at DESC LIMIT 1",
                    [],
                    |row| {
                        let size: i64 = row.get(1)?;
                        Ok(FirmwareRelease {
                            version: row.get(0)?,
                            size: u64::try_from(size).unwrap_or(0),
                            sha256_hex: row.get(2)?,
                            signature_hex: row.get(3)?,
                            rollout_percent: row.get(4)?,
                            created_millis: row.get(5)?,
                        })
                    },
                )
                .optional()
                .map_err(FacilitatorError::from)
        })
    }

    pub(crate) fn firmware_exists(&self, version: &str) -> Result<bool, FacilitatorError> {
        self.with_connection(|connection| {
            let found: Option<String> = connection
                .query_row(
                    "SELECT version FROM firmware_releases WHERE version = ?1",
                    params![version],
                    |row| row.get(0),
                )
                .optional()?;
            Ok(found.is_some())
        })
    }

    pub(crate) fn record_device_firmware(
        &self,
        device_id: &str,
        firmware: &str,
    ) -> Result<(), FacilitatorError> {
        self.with_connection(|connection| {
            connection.execute(
                "UPDATE devices SET firmware = ?1 WHERE device_id = ?2",
                params![firmware, device_id],
            )?;
            Ok(())
        })
    }
}

#[cfg(test)]
mod tests {
    use super::{cohort, pod_trust_header};

    #[test]
    fn the_pod_header_carries_the_ca_key_and_url() {
        let header = pod_trust_header(
            "-----BEGIN CERTIFICATE-----\nABC\n-----END CERTIFICATE-----\n",
            "04ab CD",
            "https://desk.local:8791/",
        );
        assert!(header.contains(
            "R\"PEM(-----BEGIN CERTIFICATE-----\nABC\n-----END CERTIFICATE-----\n)PEM\""
        ));
        assert!(header.contains("PROPERTY_FIRMWARE_PUBKEY_HEX[] = \"04abCD\""));
        assert!(header.contains("FACILITATOR_URL[] = \"https://desk.local:8791\""));
    }

    #[test]
    fn cohorts_are_stable_and_spread_out() {
        assert_eq!(cohort("pod-1", "1.0"), cohort("pod-1", "1.0"));
        let buckets: std::collections::HashSet<u8> = (0..200)
            .map(|index| cohort(&format!("pod-{index}"), "1.0"))
            .collect();
        assert!(buckets.len() > 50, "hash spreads devices across buckets");
        assert!(buckets.iter().all(|bucket| *bucket < 100));
    }
}
